name: mon_budget
description: "Application de gestion de budget"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  fl_chart: ^0.65.0
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_slidable: ^3.0.1
  # flutter_speed_dial: ^7.0.0
  shared_preferences: ^2.2.2
  awesome_notifications: ^0.8.2
  heroicons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
